---
title: "Earthquakes"
output: html_notebook
---

I created a dashboard in Tableau using the earthquake dataset and now I'm trying to create some visualizations in the RStudio with the same dataset to see what I can see.

```{r}
# Install and load necessary packages
install.packages(c("ggplot2", "maps", "readxl"))
library(ggplot2)
library(maps)
library(readxl)

# Load earthquake dataset
quakes <- read_excel("C:\\Users\\dsmit\\Documents\\Portfolio_Projects\\R\\Earthquakes\\Mag6PlusEarthquakes_1900-2013.xlsx")

# Set the background color and font color
theme_custom <- theme(
  plot.background = element_rect(fill = "black"),
  panel.background = element_rect(fill = "black"),
  legend.text = element_text(color = "white"),
  legend.title = element_text(color = "white"),
  axis.text = element_text(color = "white"),
  axis.title = element_text(color = "white")
)

# Create a ggplot with a global map and color contrast for earthquake intensities
gg_global_map <- ggplot() +
  borders("world", colour = "white", fill = NA) +
  geom_point(data = quakes, aes(x = longitude, y = latitude, color = mag), size = 2) +
  scale_color_gradient(low = "lightblue", high = "blue") +
  labs(title = "Global Earthquake Map with Intensity",
       subtitle = "Using ggplot2 in RStudio",
       x = "Longitude",
       y = "Latitude",
       color = "Magnitude") +
  theme_minimal() +
  theme_custom

# Print the global map with color contrast
print(gg_global_map)


```


```{r}
ggplot(quakes, aes(x = mag)) +
  geom_histogram(binwidth = 0.1, fill = "green", color = "white", alpha = 0.7) +
  scale_fill_gradient(low = "yellow", high = "red") +
  labs(title = "Histogram of Earthquake Magnitudes",
       x = "Magnitude",
       y = "Frequency") +
  theme_minimal() +
  theme_custom

```
```{r}
# Create a ggplot with a time series of earthquakes by magnitude
gg_time_series <- ggplot(quakes, aes(x = Date, y = ..count.., color = as.factor(mag), group = as.factor(mag))) +
  geom_area(stat = "count", size = 0.5, alpha = 0.7) +
  labs(title = "Time Series of Earthquakes by Magnitude",
       subtitle = "Using ggplot2 in RStudio",
       x = "Date",
       y = "Total Earthquakes",
       color = "Magnitude") +
  scale_color_discrete(name = "Magnitude") +
  theme_minimal() +
  theme_custom

# Print the time series plot
print(gg_time_series)
```





